name_smg = input("Enter your name: ")
age_smg = input("Enter your age: ")
course_smg = input("Enter your course: ")
university_smg = input("Enter your university: ")
print("\n----- STUDENT PROFILE -----")
print("Name:", name_smg)
print("Age:", age_smg)
print("Course:", course_smg)
print("University:", university_smg)
